name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker compose up -d
      - run: docker compose run --rm petstore_client pnpm install --frozen-lockfile
      - run: docker compose run --rm petstore_client pnpm run --if-present lint
      - run: docker compose run --rm petstore_client pnpm test
      - run: docker compose run -e=CI=true --rm petstore_client pnpm run --if-present build
